# Generated by Django 5.0.2 on 2025-01-27 10:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ride_Bookings',
            fields=[
                ('booking_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ride_booking_date', models.DateField(auto_now_add=True)),
                ('ride_booking_date_arrive', models.DateField()),
                ('ride_booking_date_leave', models.DateField()),
                ('ride_booking_adults', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ride_booking_children', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ride_booking_oap', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ride_total_cost', models.FloatField(default=0)),
                ('ride_points', models.IntegerField(default=0)),
                ('ride_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
