# Generated by Django 5.0.2 on 2024-12-12 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride_Bookings',
            fields=[
                ('booking_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ride_booking_date', models.DateField(auto_now_add=True)),
                ('ride_booking_date_arrive', models.DateField()),
                ('ride_booking_date_leave', models.DateField()),
                ('ride_booking_adults', models.IntegerField(default=0)),
                ('ride_booking_children', models.IntegerField(default=0)),
                ('ride_booking_oap', models.IntegerField(default=0)),
                ('ride_total_cost', models.FloatField(default=0)),
                ('ride_points', models.IntegerField(default=0)),
                ('ride_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
