# Generated by Django 5.0.2 on 2024-12-29 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ride_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_bookings',
            name='ride_booking_adults',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ride_bookings',
            name='ride_booking_children',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ride_bookings',
            name='ride_booking_oap',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
